"""Connector spec Pydantic models — describe how to call a third-party data API.

ConnectorCopilot generates these automatically from raw API documentation text.
They can be serialised to JSON and stored in src/sources/catalog.json or the DB.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AuthType(str, Enum):
    API_KEY_HEADER = "api_key_header"
    API_KEY_QUERY = "api_key_query"
    BEARER = "bearer"
    NONE = "none"


class EndpointSpec(BaseModel):
    """Describes a single API endpoint and its parameters."""

    name: str                            # e.g. "quote", "fundamentals"
    path: str                            # e.g. "/query"
    method: str = "GET"
    params: dict[str, str] = Field(default_factory=dict)  # param_name → description
    response_path: str | None = None     # JSONPath to data, e.g. "$.Global Quote"


class ConnectorSpec(BaseModel):
    """Full description of a data provider connector — generated by ConnectorCopilot."""

    provider_id: str
    display_name: str
    base_url: str
    auth_type: AuthType
    auth_param: str | None = None        # header/query-param name for the API key
    endpoints: list[EndpointSpec] = Field(default_factory=list)
    field_mapping: dict[str, str] = Field(default_factory=dict)  # external_field → canonical_field
    notes: str | None = None
    generated_by: str = "connector_copilot"
    generated_at: datetime
